branch-defaults:
  main:
    environment: env-transport-model-app
global:
  application_name: transport-modeling-guide
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: ap-northeast-1
  sc: git